name: C

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: |
          wget https://github.com/frida/frida/releases/download/12.11.12/frida-gum-devkit-12.11.12-linux-x86_64.tar.xz -O frida-gum.tar.xz && tar xJvf frida-gum.tar.xz && \
          meson setup build
        env:
          CC: gcc
      - run: meson test -C build -v
